version: '3.7'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:5.7.12'
    environment:
      MYSQL_DATABASE: petty
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  #    healthcheck:
  #      test: ["CMD-SHELL", "mysql -uroot -ppassword"]
  #      interval: 1m30s
  #      timeout: 30s
  #      retries: 5
  #      start_period: 30s

  ###< doctrine/doctrine-bundle ###
  app:
    build:
      context: ./
      dockerfile: ./Petty-Care-Back/docker/Dockerfile
    image: petty-care:latest
    depends_on:
      - database
    ports:
      - "8000:8000"

  db_wordpress:
    platform: linux/x86_64
    image: mariadb
    volumes:
      - ./datas:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin_wordpress:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  wordpress:
    build:
      context: ./
      dockerfile: ./Petty-Care-Wordpress/docker/Dockerfile
    depends_on:
      - db_wordpress
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8050:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db-data:
